### ISSUE TITLE
Crash before downloading apps

### ISSUE THREAD

**Issue by SlimSoftware** [SlimSoftware/sUpdater#22]
sUpdater sometimes crashes (seems like a timing problem) when installing updates/apps, just before anything is downloaded. In the Event Viewer the following exception info can be found:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(System.Windows.DependencyProperty)
   at System.Windows.Controls.Control.get_Foreground()
   at sUpdater.LogPage.AppendLine(System.String)
   at sUpdater.LogPage.OnLogAppend(System.Object, sUpdater.Models.LogAppendEventArgs)
   at sUpdater.Models.Log.Append(System.String, LogLevel)
   at sUpdater.Models.Application+<Download>d__83.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at sUpdater.UpdaterPage+<>c__DisplayClass4_0+<<InstallButton_Click>b__0>d.MoveNext()
```

**Comment by SlimSoftware** [comment]
Fixed in d8a8b25ae33126800f126a6ed2ee126c81035f52
